// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetakesAllocatorCore.Db;

#nullable disable

namespace RetakesAllocator.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("RetakesAllocatorCore.Db.UserSetting", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("EnemyStuffTeamPreference")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponPreferences")
                        .HasMaxLength(10000)
                        .HasColumnType("text");

                    b.Property<bool>("ZeusEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
